### ISSUE TITLE
setMinWordLength gives an exception

### ISSUE THREAD

**Issue by lfdversluis** [kennycason/kumo#16]
Hey, nice library.

I loaded some text into it and settings ``frequencyAnalyzer.setMinWordLength(2);`` for words such as "ok" and "gg", but this gives me an exception:
```
java.lang.IllegalArgumentException: Width (0) and height (14) cannot be <= 0
	at java.awt.image.DirectColorModel.createCompatibleWritableRaster(DirectColorModel.java:1016)
	at java.awt.image.BufferedImage.<init>(BufferedImage.java:340)
	at wordcloud.Word.<init>(Word.java:39)
	at wordcloud.WordCloud.buildWord(WordCloud.java:260)
	at wordcloud.WordCloud.buildwords(WordCloud.java:247)
	at wordcloud.WordCloud.build(WordCloud.java:107)
	at CloudCreator.main(CloudCreator.java:56)
```
where line 56 is ``wordCloud.build(wordFrequencies);``

**Comment by lfdversluis** [comment]
Might be related to the empty string issue #14

**Comment by kennycason** [comment]
fixed.
