### ISSUE TITLE
Example is crashing with java.lang.VerifyError overrides final method visit

### ISSUE THREAD

**Issue by liar666** [kennycason/kumo#41]
I'm trying to run "rectangle" example (nb 3) from:
https://github.com/kennycason/kumo
but I get:
```
Exception in thread "main" java.lang.VerifyError: class net.sf.cglib.core.DebuggingClassWriter overrides final method visit.(IILjava/lang/String;Ljava/lang/String;Ljava/lang/String;[Ljava/lang/String;)V
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at net.sf.cglib.core.AbstractClassGenerator.<init>(AbstractClassGenerator.java:38)
        at net.sf.cglib.core.KeyFactory$Generator.<init>(KeyFactory.java:127)
        at net.sf.cglib.core.KeyFactory.create(KeyFactory.java:112)
        at net.sf.cglib.core.KeyFactory.create(KeyFactory.java:108)
        at net.sf.cglib.core.KeyFactory.create(KeyFactory.java:104)
        at net.sf.cglib.proxy.Enhancer.<clinit>(Enhancer.java:69)
        at ch.lambdaj.proxy.ProxyUtil.createEnhancer(ProxyUtil.java:89)
        at ch.lambdaj.proxy.ProxyUtil.createProxy(ProxyUtil.java:49)
        at ch.lambdaj.function.argument.ArgumentsFactory.createPlaceholder(ArgumentsFactory.java:52)
        at ch.lambdaj.function.argument.ArgumentsFactory.registerNewArgument(ArgumentsFactory.java:45)
        at ch.lambdaj.function.argument.ArgumentsFactory.createArgument(ArgumentsFactory.java:39)
        at ch.lambdaj.function.argument.ArgumentsFactory.createArgument(ArgumentsFactory.java:31)
        at ch.lambdaj.Lambda.on(Lambda.java:44)
        at com.kennycason.kumo.WordCloud.maxFrequency(WordCloud.java:259)
        at com.kennycason.kumo.WordCloud.buildWords(WordCloud.java:228)
        at com.kennycason.kumo.WordCloud.build(WordCloud.java:90)
...
```

**Comment by liar666** [comment]
OK thanks to:
http://stackoverflow.com/questions/9366403/java-lang-verifyerror-class-net-sf-cglib-core-debuggingclasswriter#9447713

I discovered this comes from a conflict with 2 different versions of cglib in my classpath.

One is included in kumo.

The solution for me was to unjar kumo.jar, remove all the included libs that enters in conflict with my local versions, then recreate the (lightened) kumo jar.

**Comment by kennycason** [comment]
@liar666 Thanks for pointing this out, I'll investigate "lightening the jar" as well on my end.
